import type { StudentDocumentRecord } from "@/lib/document-center/types";

export const MOCK_STUDENT_DOCUMENTS: StudentDocumentRecord[] = [
  {
    id: "doc-001",
    studentId: "stu-001",
    studentName: "Aisha Noor",
    classId: "grade-6-a",
    className: "Grade 6A",
    guardianName: "Mariam Noor",
    guardianPhone: "+254 712 301 201",
    guardianEmail: "mariam.noor@example.com",
    category: "identity",
    documentName: "Birth Certificate",
    fileName: "aisha_birth_certificate.pdf",
    status: "verified",
    uploadedAt: "2026-07-02T08:20:00.000Z",
    verifiedAt: "2026-07-03T09:15:00.000Z",
    rejectedAt: null,
    expiresAt: "2027-07-03T00:00:00.000Z",
    reminderLeadDays: 30,
    reminderEnabled: true,
    nextReminderAt: "2027-06-03T00:00:00.000Z",
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-03T09:15:00.000Z",
    timeline: [
      {
        id: "evt-001",
        at: "2026-07-02T08:20:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Birth certificate file received at reception desk.",
        fromStatus: "missing",
        toStatus: "uploaded"
      },
      {
        id: "evt-002",
        at: "2026-07-03T09:15:00.000Z",
        actorName: "School Principal",
        actorRole: "PRINCIPAL",
        action: "Document verified",
        note: "Identity document confirmed against application details.",
        fromStatus: "uploaded",
        toStatus: "verified"
      }
    ]
  },
  {
    id: "doc-002",
    studentId: "stu-001",
    studentName: "Aisha Noor",
    classId: "grade-6-a",
    className: "Grade 6A",
    guardianName: "Mariam Noor",
    guardianPhone: "+254 712 301 201",
    guardianEmail: "mariam.noor@example.com",
    category: "medical",
    documentName: "Immunization Card",
    fileName: "aisha_immunization_card.pdf",
    status: "uploaded",
    uploadedAt: "2026-07-10T12:05:00.000Z",
    verifiedAt: null,
    rejectedAt: null,
    expiresAt: "2026-08-15T00:00:00.000Z",
    reminderLeadDays: 14,
    reminderEnabled: true,
    nextReminderAt: "2026-08-01T00:00:00.000Z",
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-10T12:05:00.000Z",
    timeline: [
      {
        id: "evt-003",
        at: "2026-07-10T12:05:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Medical card submitted for pending verification.",
        fromStatus: "missing",
        toStatus: "uploaded"
      }
    ]
  },
  {
    id: "doc-003",
    studentId: "stu-001",
    studentName: "Aisha Noor",
    classId: "grade-6-a",
    className: "Grade 6A",
    guardianName: "Mariam Noor",
    guardianPhone: "+254 712 301 201",
    guardianEmail: "mariam.noor@example.com",
    category: "consent",
    documentName: "Media Consent Form",
    fileName: null,
    status: "missing",
    uploadedAt: null,
    verifiedAt: null,
    rejectedAt: null,
    expiresAt: null,
    reminderLeadDays: 7,
    reminderEnabled: true,
    nextReminderAt: null,
    lastReminderAt: null,
    missingReminderEveryDays: 5,
    nextMissingReminderAt: "2026-07-30T08:00:00.000Z",
    lastMissingReminderAt: "2026-07-25T08:00:00.000Z",
    lastUpdatedAt: "2026-07-25T08:00:00.000Z",
    timeline: [
      {
        id: "evt-004",
        at: "2026-07-25T08:00:00.000Z",
        actorName: "System Reminder",
        actorRole: "SYSTEM",
        action: "Missing document reminder queued",
        note: "Guardian reminder scheduled because consent form is still missing.",
        fromStatus: null,
        toStatus: null
      }
    ]
  },
  {
    id: "doc-004",
    studentId: "stu-002",
    studentName: "Liam Otieno",
    classId: "grade-7-b",
    className: "Grade 7B",
    guardianName: "Peter Otieno",
    guardianPhone: "+254 701 223 344",
    guardianEmail: "p.otieno@gmail.com",
    category: "admission",
    documentName: "Admission Letter",
    fileName: "liam_admission_letter.pdf",
    status: "verified",
    uploadedAt: "2026-06-14T10:20:00.000Z",
    verifiedAt: "2026-06-15T09:40:00.000Z",
    rejectedAt: null,
    expiresAt: "2026-09-01T00:00:00.000Z",
    reminderLeadDays: 21,
    reminderEnabled: true,
    nextReminderAt: "2026-08-11T00:00:00.000Z",
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-06-15T09:40:00.000Z",
    timeline: [
      {
        id: "evt-005",
        at: "2026-06-14T10:20:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Admission letter attached by reception.",
        fromStatus: "missing",
        toStatus: "uploaded"
      },
      {
        id: "evt-006",
        at: "2026-06-15T09:40:00.000Z",
        actorName: "System Administrator",
        actorRole: "SUPER_ADMIN",
        action: "Document verified",
        note: "Admission letter approved for onboarding.",
        fromStatus: "uploaded",
        toStatus: "verified"
      }
    ]
  },
  {
    id: "doc-005",
    studentId: "stu-002",
    studentName: "Liam Otieno",
    classId: "grade-7-b",
    className: "Grade 7B",
    guardianName: "Peter Otieno",
    guardianPhone: "+254 701 223 344",
    guardianEmail: "p.otieno@gmail.com",
    category: "finance",
    documentName: "Fee Agreement",
    fileName: "liam_fee_agreement_scan.jpg",
    status: "rejected",
    uploadedAt: "2026-07-18T14:30:00.000Z",
    verifiedAt: null,
    rejectedAt: "2026-07-19T08:10:00.000Z",
    expiresAt: null,
    reminderLeadDays: 14,
    reminderEnabled: true,
    nextReminderAt: null,
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: "2026-07-31T08:00:00.000Z",
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-19T08:10:00.000Z",
    timeline: [
      {
        id: "evt-007",
        at: "2026-07-18T14:30:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Fee agreement image submitted for validation.",
        fromStatus: "missing",
        toStatus: "uploaded"
      },
      {
        id: "evt-008",
        at: "2026-07-19T08:10:00.000Z",
        actorName: "School Principal",
        actorRole: "PRINCIPAL",
        action: "Document rejected",
        note: "Illegible amount field; re-upload with clearer scan requested.",
        fromStatus: "uploaded",
        toStatus: "rejected"
      }
    ]
  },
  {
    id: "doc-006",
    studentId: "stu-003",
    studentName: "Noah Hassan",
    classId: "grade-8-a",
    className: "Grade 8A",
    guardianName: "Fatuma Hassan",
    guardianPhone: "+254 722 987 654",
    guardianEmail: "f.hassan@gmail.com",
    category: "academic",
    documentName: "Previous Report Card",
    fileName: "noah_previous_report_card.pdf",
    status: "expired",
    uploadedAt: "2026-03-11T09:00:00.000Z",
    verifiedAt: "2026-03-13T11:45:00.000Z",
    rejectedAt: null,
    expiresAt: "2026-07-10T00:00:00.000Z",
    reminderLeadDays: 30,
    reminderEnabled: true,
    nextReminderAt: null,
    lastReminderAt: "2026-07-09T08:00:00.000Z",
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-10T00:00:00.000Z",
    timeline: [
      {
        id: "evt-009",
        at: "2026-03-11T09:00:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Initial academic transcript uploaded.",
        fromStatus: "missing",
        toStatus: "uploaded"
      },
      {
        id: "evt-010",
        at: "2026-03-13T11:45:00.000Z",
        actorName: "School Principal",
        actorRole: "PRINCIPAL",
        action: "Document verified",
        note: "Transcript accepted for placement review.",
        fromStatus: "uploaded",
        toStatus: "verified"
      },
      {
        id: "evt-011",
        at: "2026-07-10T00:00:00.000Z",
        actorName: "System Reminder",
        actorRole: "SYSTEM",
        action: "Document expired",
        note: "Academic transcript validity window elapsed.",
        fromStatus: "verified",
        toStatus: "expired"
      }
    ]
  },
  {
    id: "doc-007",
    studentId: "stu-003",
    studentName: "Noah Hassan",
    classId: "grade-8-a",
    className: "Grade 8A",
    guardianName: "Fatuma Hassan",
    guardianPhone: "+254 722 987 654",
    guardianEmail: "f.hassan@gmail.com",
    category: "identity",
    documentName: "Guardian ID Copy",
    fileName: "noah_guardian_id.pdf",
    status: "uploaded",
    uploadedAt: "2026-07-21T15:20:00.000Z",
    verifiedAt: null,
    rejectedAt: null,
    expiresAt: null,
    reminderLeadDays: 10,
    reminderEnabled: true,
    nextReminderAt: null,
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-21T15:20:00.000Z",
    timeline: [
      {
        id: "evt-012",
        at: "2026-07-21T15:20:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Guardian ID uploaded for review.",
        fromStatus: "missing",
        toStatus: "uploaded"
      }
    ]
  },
  {
    id: "doc-008",
    studentId: "stu-004",
    studentName: "Emma Kariuki",
    classId: "grade-6-a",
    className: "Grade 6A",
    guardianName: "Samuel Kariuki",
    guardianPhone: "+254 722 111 222",
    guardianEmail: "s.kariuki@outlook.com",
    category: "consent",
    documentName: "Medical Consent Form",
    fileName: "emma_medical_consent.pdf",
    status: "verified",
    uploadedAt: "2026-07-12T07:30:00.000Z",
    verifiedAt: "2026-07-12T15:00:00.000Z",
    rejectedAt: null,
    expiresAt: "2026-08-05T00:00:00.000Z",
    reminderLeadDays: 10,
    reminderEnabled: true,
    nextReminderAt: "2026-07-26T00:00:00.000Z",
    lastReminderAt: null,
    missingReminderEveryDays: 7,
    nextMissingReminderAt: null,
    lastMissingReminderAt: null,
    lastUpdatedAt: "2026-07-12T15:00:00.000Z",
    timeline: [
      {
        id: "evt-013",
        at: "2026-07-12T07:30:00.000Z",
        actorName: "Grace Wanjiku",
        actorRole: "RECEPTION",
        action: "Document uploaded",
        note: "Consent form submitted by guardian.",
        fromStatus: "missing",
        toStatus: "uploaded"
      },
      {
        id: "evt-014",
        at: "2026-07-12T15:00:00.000Z",
        actorName: "System Administrator",
        actorRole: "SUPER_ADMIN",
        action: "Document verified",
        note: "Consent signatures confirmed.",
        fromStatus: "uploaded",
        toStatus: "verified"
      }
    ]
  }
];
